---

- hosts: coderepo
  become: true

  pre_tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

  post_tasks:
    - name: Proxy gitea trafic thru nginx
      copy:
        content: |
          server {
              listen 80;
              listen [::]:80;
              server_name code.tinkerit.vn;
              location / {
                  proxy_pass       http://localhost:3000;
                  proxy_set_header Host      $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
        dest: /etc/nginx/conf.d/gitea.conf
        owner: root
        group: root
        mode: '0644'
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  roles:
    - role: nginx

    - role: gitea
      gitea_version: "1.16.7"
      gitea_user: "gitea"
      # enable maintenance using `gitea` account
      gitea_shell: "/bin/ba`sh"
      gitea_home: "/var/lib/gitea"
      gitea_http_domain: code.tinkerit.vn
      gitea_root_url: http://code.tinkerit.vn
      gitea_protocol: http
      gitea_http_listen: 0.0.0.0
      gitea_http_port: 3000
      gitea_disable_http_git: false
      gitea_offline_mode: true
      # SSH server configuration
      gitea_ssh_listen: 0.0.0.0
      gitea_ssh_port: 2222
      # For URLs rendering again
      gitea_ssh_domain: code.tinkerit.vn
      gitea_start_ssh: true
      gitea_secret_key: 3sp00ky5me
      gitea_disable_gravatar: true
      # To make at least your first user register
      gitea_disable_registration: true
      gitea_require_signin: true
      gitea_enable_captcha: true
      gitea_show_user_email: false

    # - role: gitlab
    #   gitlab_domain: coderepo.tinkerit.vn
    #   gitlab_external_url: "http://{{ gitlab_domain }}/"
    #   gitlab_edition: "gitlab-ce"
    #   gitlab_version: "14.10.1-ce.0"
    #   gitlab_redirect_http_to_https: false

